### ISSUE TITLE
软件适用性

### ISSUE THREAD

**Issue by Mc-Snake** [HIllya51/Magpie9_win7#6]
非常感谢大佬，虽说能提升gal画质就很好了，但我还是想问一下，这个有没有适配一般的游戏，比如mc

**Comment by HIllya51** [comment]
此程序仅是对 https://github.com/Blinue/Magpie 0.9.1版本在windows7系统上的适配，没有在galgame以外的游戏上进行过测试。
若你的系统是win10/11而不是win7，建议不要使用此程序，而是使用原版。

**Comment by Mc-Snake** [comment]
感谢大佬，我知道大佬这个是自己改的适配win7，没有适配gal以外的游戏确实可惜，不知道gal的动图场景是不是也可以

**Comment by Mc-Snake** [comment]
像是戏画社的作品，或者是小粥姐妹，甚至更老的的游戏河原崎家の一族

**Comment by HIllya51** [comment]
不知道 我没试过 但一般来说应该是可以的

**Comment by Mc-Snake** [comment]
好的
