### ISSUE TITLE
VMware win7虚拟器初始化失败

### ISSUE THREAD

**Issue by Estelle-Bright** [HIllya51/Magpie9_win7#7]
系统用的是绯月上大佬做的精简版（第一次提issue，还望多多海涵）
[Uploading Magpie.log…]()
![错误截图](https://github.com/HIllya51/Magpie9_win7/assets/142033656/41c53209-ac38-4ec0-a8ad-59a477f81583)
![错误截图2](https://github.com/HIllya51/Magpie9_win7/assets/142033656/d3a96ed7-1fda-47ec-bcb6-834cf8712769)
![虚拟机配置](https://github.com/HIllya51/Magpie9_win7/assets/142033656/424f60d7-219d-4fae-9536-402f355783f0)
[Uploading 镜像.txt…]()

**Comment by HIllya51** [comment]
缺少dll依赖，鉴定为精简版系统缺少相关依赖库。
请换成正常系统，并安装vcredist+DirectX。
只安装vcredist+DirectX也有可能也能运行，但最好还是换成正常系统。
